### ISSUE TITLE
kindly add my laravel preset package for vuetify using InertiaJS and laravel

### ISSUE THREAD

**Issue by codeitlikemiley** [vuetifyjs/awesome-vuetify#41]
Uses InertiaJS and Vue 

Advantage : Allows You to Use Dynamic Components with vuetify on a Laravel Project 

Packagist Link:
https://packagist.org/packages/codeitlikemiley/vuetified-laravel-preset

Github:
https://github.com/codeitlikemiley/vuetified-laravel-preset

Video Tutorial How to Install:
https://www.youtube.com/watch?v=85ZDW2cy5Eg&feature=youtu.be

**Comment by codeitlikemiley** [comment]
works with latest update of laravel 6.0 :)

**Comment by johnleider** [comment]
Create a PR please.
